[project]
name = "env_sourcer"
version = "0.0.1"
requires-python = ">= 3.11"
description = "library to source environmental variables easily through different environments"
dependencies = []

[project.optional-dependencies]
tests = [
    "pytest"
]